config/routes.rb
Rails.application.routes.draw do
  
 

  mount Ckeditor::Engine => '/ckeditor'
  resources :announcements
  resources :quizzes
  resources :lessons do
    collection {post :sort}
  end
  resources :units
  resources :tracks
  resources :badges
  resources :resources
  get 'admin/show'
  get 'projects/add', to: 'projects#add'

  resources :classrooms do
    collection { post :importcadata }
  end

  resources :events do
      resources :registrations, only: [:create, :destroy, :add_students_by_classroom, :add_students_by_school] do
          
          resources :signatures, only: [:new, :create, :send] do
              collection do
                  post :callbacks
                  post :sendsigrequest
              end
          end
          
          
          member do
              post :sign
              get :accept
              get :decline
          end
      end
      
      member do
          get :manage
          post :publish
          post :unpublish
          post :add_students_by_classroom
          post :add_students_by_school
      end
  end
  
  
  
  devise_for :users,
    controllers: { registrations: "users/registrations", sessions: "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'static_pages#home'
  

  get 'projects/add', to: 'projects#add'
  get 'editor', to: 'static_pages#editor'

 

  post 'projects/import', to: 'projects#import'

  post '/signatures/callbacks', to: 'signatures#callbacks'
  get '/signatures/callbacks', to: 'signatures#callbacks'
  post 'signatures/authorize_adobe', to: 'signatures#authorize_adobe'
  
  post '/users/invite_teacher', to: 'users#invite_teacher'

  resources :projects
  resources :schools
  resources :teachers
  resources :users  do
      member do
          get :toggle_approved
      end
  end

  resources :classrooms do
      member do 
        get :export_attendance
      end

      resources :enrollments, only: [:create, :destroy, :verify] do
        collection do
          post "verify"
        end
      end
  end
  
  resources :attendance_data do
          member do
              get :toggle_present
          end
  end

  resources :attendance_lists do
      
      member do
          post :toggle_status
          get :record
      end
      
      resources :attendance_data do
          
          member do
              get :mark_as_present
              get :toggle_present
          end
      end

  end

  resources :students do
      collection { post :import }
  end
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :mark_as_read
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  
  resources :notifications, only: [:index, :show] do
      member do
          post :trash
          post :untrash
          post :mark_as_read
          post :mark_as_unread
      end
  end

  resources :messages, only: [:new, :create]
  
  

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end

end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                    class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_form.html.erb
<%= simple_form_for :conversation, url: :conversations do |f|%>
    <%= f.input :recipients, class: 'form-control'%>
    <%= f.input :subject, class: 'form-control' %>
    <%= f.input :body, as: :text, class: 'form-control'%>
    <%= f.button :submit, "Start Conversation", class: 'btn btn-primary'%>
    <%= f.button :submit, 'Cancel', type: :reset, class: 'btn btn-danger'%>
<%end%>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
          <h1> Mailbox </h1>
     </div> 
    </div>
  </div>
</div>


<div class="container">
  <p id="notice"><%= notice %></p>
    
    <p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

    <div class="row">
      <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
          <%= mailbox_section 'inbox', @box %>
          <%= mailbox_section 'sent', @box %>
          <%= mailbox_section 'trash', @box %>
        </ul>
      </div>

      <div class="col-sm-9">
        <% if @box == 'trash' %>
          <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                         data: {confirm: 'Are you sure?'} %></p>
        <% end %>
        <ul class="list-group">
          <%= render partial: 'conversations/conversation', collection: @conversations %>
        </ul>

        <%= will_paginate %>
      </div>
    </div>
    
</div>

app/views/conversations/new.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
          <h1> Start Conversation </h1>
     </div> 
    </div>
  </div>
</div>


<div class="container">
  <p id="notice"><%= notice %></p>
    <%= render 'form'%>
</div>

app/views/conversations/show.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
          <h1>Chatting with
          <%= render 'conversations/participants', conversation: @conversation %>
          </h1>
     </div> 
    </div>
  </div>
</div>

<div class="container">


<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
          
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>

</div>