config/routes.rb
Rails.application.routes.draw do
  
 

  mount Ckeditor::Engine => '/ckeditor'
  resources :announcements
  resources :quizzes
  resources :lessons do
    collection {post :sort}
  end
  resources :units
  resources :tracks
  resources :badges
  resources :resources
  get 'admin/show'
  get 'projects/add', to: 'projects#add'

  resources :classrooms do
    collection { post :importcadata }
  end

  resources :events do
      resources :registrations, only: [:create, :destroy, :add_students_by_classroom, :add_students_by_school] do
          
          resources :signatures, only: [:new, :create, :send] do
              collection do
                  post :callbacks
                  post :sendsigrequest
              end
          end
          
          
          member do
              post :sign
              get :accept
              get :decline
          end
      end
      
      member do
          get :manage
          post :publish
          post :unpublish
          post :add_students_by_classroom
          post :add_students_by_school
      end
  end
  
  
  
  devise_for :users,
    controllers: { registrations: "users/registrations", sessions: "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'static_pages#home'
  

  get 'projects/add', to: 'projects#add'
  get 'editor', to: 'static_pages#editor'

 

  post 'projects/import', to: 'projects#import'

  post '/signatures/callbacks', to: 'signatures#callbacks'
  get '/signatures/callbacks', to: 'signatures#callbacks'
  post 'signatures/authorize_adobe', to: 'signatures#authorize_adobe'
  
  post '/users/invite_teacher', to: 'users#invite_teacher'

  resources :projects
  resources :schools
  resources :teachers
  resources :users  do
      member do
          get :toggle_approved
      end
  end

  resources :classrooms do
      member do 
        get :export_attendance
      end

      resources :enrollments, only: [:create, :destroy, :verify] do
        collection do
          post "verify"
        end
      end
  end
  
  resources :attendance_data do
          member do
              get :toggle_present
          end
  end

  resources :attendance_lists do
      
      member do
          post :toggle_status
          get :record
      end
      
      resources :attendance_data do
          
          member do
              get :mark_as_present
              get :toggle_present
          end
      end

  end

  resources :students do
      collection { post :import }
  end
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :mark_as_read
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  
  resources :notifications, only: [:index, :show] do
      member do
          post :trash
          post :untrash
          post :mark_as_read
          post :mark_as_unread
      end
  end

  resources :messages, only: [:new, :create]
  
  

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_filter :authenticate_user!
    helper_method :mailbox, :notification
    
    def trash
        notification.move_to_trash(current_user)
        redirect_to :notifications
    end
    
    def untrash
        notification.untrash(current_user)
        redirect_to :notifications
    end
    
    def show
        notification.mark_as_read(current_user)
    end
    
    
    def mark_as_read
        notification.mark_as_read(current_user)
        redirect_to :notifications
    end
    
    def mark_as_unread
        notification.mark_as_unread(current_user)
        redirect_to :notifications
    end

    
    private
    
    def mailbox
        @mailbox ||= current_user.mailbox
    end
    
    
    def notification
        @notification ||= mailbox.notifications.find(params[:id])
    end
    
    
    
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<%= content_tag_for(:li, notification, class: "list-group-item") do |notification|%>
  
    <%= link_to notification.subject, notification_path(notification)%>
    |
    <% if notification.is_read?(current_user)%>
      <%= link_to 'Mark Unread', mark_as_unread_notification_path(notification), method: :post%>
    <% elsif notification.is_unread?(current_user)%>
      <%= link_to 'Mark Read', mark_as_read_notification_path(notification), method: :post%>
    <%end%>    

<%end%>

app/views/notifications/index.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
          <h1> Notifications </h1>
     </div> 
    </div>
  </div>
</div>


<div class="container">
  <p id="notice"><%= notice %></p>
  

    <div class="col-lg-8 col-lg-offset-2">
      <ul class = "list-group"> <%= render partial: "notification", collection: mailbox.notifications %> </ul>
    </div>
    

</div>

app/views/notifications/show.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
         <h1> <%= notification.subject %> </h1>
     </div> 
    </div>
  </div>
</div>




<div class="container">
  <p id="notice"><%= notice %></p>


      <ul>
        <%= content_tag_for(:li, notification) do |notification|%>
          
          <h3> <%= notification.subject%> </h3>
          <p> <%= raw notification.body %> </p>
          <%end%>
      
      </ul>
</div>