config/routes.rb
Rails.application.routes.draw do
  
 

  mount Ckeditor::Engine => '/ckeditor'
  resources :announcements
  resources :quizzes
  resources :lessons do
    collection {post :sort}
  end
  resources :units
  resources :tracks
  resources :badges
  resources :resources
  get 'admin/show'
  get 'projects/add', to: 'projects#add'

  resources :classrooms do
    collection { post :importcadata }
  end

  resources :events do
      resources :registrations, only: [:create, :destroy, :add_students_by_classroom, :add_students_by_school] do
          
          resources :signatures, only: [:new, :create, :send] do
              collection do
                  post :callbacks
                  post :sendsigrequest
              end
          end
          
          
          member do
              post :sign
              get :accept
              get :decline
          end
      end
      
      member do
          get :manage
          post :publish
          post :unpublish
          post :add_students_by_classroom
          post :add_students_by_school
      end
  end
  
  
  
  devise_for :users,
    controllers: { registrations: "users/registrations", sessions: "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'static_pages#home'
  

  get 'projects/add', to: 'projects#add'
  get 'editor', to: 'static_pages#editor'

 

  post 'projects/import', to: 'projects#import'

  post '/signatures/callbacks', to: 'signatures#callbacks'
  get '/signatures/callbacks', to: 'signatures#callbacks'
  post 'signatures/authorize_adobe', to: 'signatures#authorize_adobe'
  
  post '/users/invite_teacher', to: 'users#invite_teacher'

  resources :projects
  resources :schools
  resources :teachers
  resources :users  do
      member do
          get :toggle_approved
      end
  end

  resources :classrooms do
      member do 
        get :export_attendance
      end

      resources :enrollments, only: [:create, :destroy, :verify] do
        collection do
          post "verify"
        end
      end
  end
  
  resources :attendance_data do
          member do
              get :toggle_present
          end
  end

  resources :attendance_lists do
      
      member do
          post :toggle_status
          get :record
      end
      
      resources :attendance_data do
          
          member do
              get :mark_as_present
              get :toggle_present
          end
      end

  end

  resources :students do
      collection { post :import }
  end
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :mark_as_read
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  
  resources :notifications, only: [:index, :show] do
      member do
          post :trash
          post :untrash
          post :mark_as_read
          post :mark_as_unread
      end
  end

  resources :messages, only: [:new, :create]
  
  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :school
    
    has_many :classrooms
    has_many :enrollments, through: :classrooms
    has_many :students, through: :enrollments
    
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :current_teacher_only, only: [:edit]

  # GET /profiles
  # GET /profiles.json
  def index
#    @teachers = Teacher.all

     @q = Teacher.ransack(params[:q])
     @teachers = @q.result(distinct: true).page(params[:page]).per(12)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @teacher = Teacher.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @teacher = Teacher.new(teacher_params)
    User.where(:role => 2).each do |admin|
        admin.notify("C/I has a new teacher!","#{current_user.email} created a teacher profile" )
    end

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #POST

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end
    
    def current_teacher_only
        if @teacher == current_user.teacher || current_user.admin?
            
            else
            redirect_to root_path, :alert => "Access denied."
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
        params.require(:teacher).permit(:first_name, :last_name, :profile_name, :profile_pic_url, :about_me, :github_username, :codecademy_username, :user_id, :school_id)
    end
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-6">
  <div class="field form-group">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, :class => "form-control" %>
  </div>
  
  <div class="field form-group">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :profile_name %><br />
    <%= f.text_field :profile_name, autofocus: true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :about_me %><br>
    <%= f.text_area :about_me, :class => "form-control" %>
  </div>

  <div class="field form-group">
      <%= f.label :school %><br>
      <%= f.collection_select :school_id, School.all, :id, :school_name, :class => "form-control select2-tag" %>  
  </div>

  <div class="actions form-group">
    <%= f.submit "Save Profile", :class => "btn btn-primary" %>
  </div>

</div>
<div class="col-md-6">
  <div class="field form-group">
    <%= f.label :codecademy_username %><a href="www.codacademy.com"> Sign Up/Visit Codacademy </a><br>
    <%= f.text_field :codecademy_username, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :github_username %> <a href="www.github.com"> Sign Up/Visit Github </a><br>
    <%= f.text_field :github_username, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :devpost_username%> <a href="www.devpost.com"> Sign Up/Visit Devpost </a><br>
    <%= f.text_field :devpost_username, :class => "form-control" %>
  </div>

  </div>
  
  <div class="field form-group">
    <%= f.hidden_field :user_id, value: current_user.id%>
  </div>
</div>
  
<% end %>

app/views/teachers/edit.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
         <h1>Update Teacher Profile</h1>
     </div> 
    </div>
  </div>
</div>

 <div class="container">

     <div class="row">
        

        <%= render 'form' %>

        <div class="col-md-12">
        <%= link_to 'Back', @teacher %> | <%= link_to "Update Email/Password", edit_user_registration_path %>
        </div>
    </div>
 </div>

app/views/teachers/index.html.erb
  <div class="page-header ribbon-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
            <h1>All Teachers</h1>        
       </div> 
      </div>
    </div>
  </div>

  <div class="container">

          <p id="notice"><%= notice %></p>

          <div class="row">
            <% if current_user.try(:admin?) %>
            <div class="col-lg-6"> 
            <h4>Invite Teacher</h4>

              <%= form_tag users_invite_teacher_path do %>
              <div class="form-group">
                <%= text_field_tag(:teacher_email, "Add teacher by email...", :class => "form-control") %>
              </div>   
              
              <%= submit_tag "Invite Teacher", :class => "btn btn-default" %>
              <% end %>
            </div>
            <%end%>
              
             <div class="col-lg-6"> 
              <h4>Search For Teacher</h4>
                <%= search_form_for @q  do |f| %>
                 <div class="form-group"> 
                <%= f.search_field :last_name_cont, :autofocus => true, class: 'form-control', :placeholder => "Search for an teacher..."  %>
             </div>
              <div class="form-group"> 
                <%= f.submit "Search", :class => 'btn btn-primary' %>
              </div>
                <% end %>
            </div>
          </div>  

          <div class="row">
          <% @teachers.each do |teacher| %>
               
                  <div class="col-lg-3"> 
                     
                     <div class="panel panel-default">
                      <%= link_to teacher do %>
                      <div class="panel-body panel-project">
                        <%= image_tag teacher.user.image, :height => "50px", :class => "img-circle img-responsive panel-img-user" %>
                        <h4><%= teacher.first_name %> <%= teacher.last_name %></h4>
                      </div>
                      <%end%>
                      <div class="panel-footer">
                        <a href='https://github.com/<%=teacher.github_username%>' class="btn btn-social-icon btn-github">
                            <span class="fa fa-github"></span>
                        </a>

                        <a href='https://www.codecademy.com/<%=teacher.codecademy_username %>' class="btn btn-social-icon btn-instagram">
                            <span class="fa fa-code"></span>
                        </a>

                        <a href='https://devpost.com/<%=teacher.github_username%>' class="btn btn-social-icon btn-reddit">
                          <img src = "http://nealrs.github.io/devpost-follow-button/icon/devpost-32.png">        
                        </a>
                      </div>
                    </div>
                    
                  </div> 
             
            <% end %>
      </div>
  </div>

app/views/teachers/new.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
         <h1>Create Your Teacher Profile</h1> 
     </div> 
    </div>
  </div>
</div>

<div class="container">

     <div class="row">
      <p id="notice"><%= notice %></p>     
        <div class="col-md-12">
          <h3> Please fill the below information </h3>
          <p> Not a teacher? Create a <%= link_to 'Student Acount', new_student_path %> 
          </p> 
        </div>
        <%= render 'form' %>

         
  </div>
<div>

app/views/teachers/show.html.erb
<div class="page-header ribbon-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1><%= @teacher.first_name %> <%= @teacher.last_name %> (<%=@teacher.profile_name%>)</h1>
      </div> 
    </div>
  </div>
</div>

<div class="page-header">
  <div class="container">
    <% flash.each do |name, msg| -%>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= msg %> 
    </div>
    <%end%>

    <div class="row">
      <div class="col-lg-3">
            <%= image_tag @teacher.user.image, :class => "user-image img-rounded img-responsive"%>
      </div>

     <div class="col-lg-6">
            <h3> "<%= @teacher.about_me %>"</h3> 
            <p> <span class="fa fa-university"></span> <%= @teacher.school.school_name %></p>
            <p> <span class="fa fa-user"></span>  C/I Teacher</p> 
            <p> <span class="fa fa-map-marker"></span>   New York, New York</p> 

            <% if current_user.try(:admin?) || current_user == @teacher.user%> 
            <p> 
              <span class="fa fa-edit"></span> <%= link_to "Edit Profile", edit_teacher_path(@teacher)%> 
            </p>
            <%end%>
            
             <a href='https://github.com/<%=@teacher.github_username%>' class="btn btn-social-icon btn-github">
                <span class="fa fa-github"></span>
            </a>

            <a href='https://www.codecademy.com/<%=@teacher.codecademy_username %>' class="btn btn-social-icon btn-instagram">
                <span class="fa fa-code"></span>
            </a>

            <a href='https://devpost.com/<%=@teacher.github_username%>' class="btn btn-social-icon btn-reddit">
              <img src = "http://nealrs.github.io/devpost-follow-button/icon/devpost-32.png">         
            </a>
      </div>
</div>

</div> 
</div>


<div class="container">
  <div class="row">
    <div class="col-lg-12">

      <ul class="nav nav-pills nav-justified">
        <li class="active"><a data-toggle="pill" href="#home"><i class="fa fa-sitemap"></i> Classrooms</a></li>
        <li><a data-toggle="pill" href="#menu1"><i class="fa fa-calendar"></i> Events </a></li>
        <li><a data-toggle="pill" href="#menu2"><i class="fa fa-book"></i> Teacher Resources and Links </a></li>
        <li><a data-toggle="pill" href="#menu3"><i class="fa fa-trophy"></i> Awards </a></li>
      </ul>
      
      
    </div>

    <div class="tab-content">
      <div id="home" class="tab-pane fade in active">
        <div class="col-lg-12"> 
          <h3><%= link_to "New Classroom", new_classroom_path, :class => "btn btn-primary"%> </h3>
        </div> 

        <% @teacher.classrooms.each do |classroom| %>
        <div class="col-lg-3">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                       <%=classroom.name%>: <%=classroom.teacher.last_name%>  
                       
                    </div>
                    <div class="panel-body">

                                 <h4> <%=classroom.name%></h4>
                                 <p> Teacher: <%=classroom.teacher.last_name%>  </p>
                                 <p> School: <%=classroom.school.school_name%> </p>
                                 <p> Students Enrolled: <%=classroom.verified_enrollments.count%>  </p>
                                 <p> Class Attendance: <%= classroom.percent_present %></p>
                    </div>
                    <div class="panel-footer">
                         <%= link_to "View Classroom", classroom%>
                    </div>
                </div>
            </div>  
        <% end %>
    </div>

    <div id="menu1" class="tab-pane fade">
      <div class="col-lg-12"> 
          <h3><%= link_to "New Event", new_event_path, :class => "btn btn-primary"%> </h3>
        </div> 

        

    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Menu 2</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Menu 3</h3>
      <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    </div>
  </div>


</div>
</div>