config/routes.rb
Rails.application.routes.draw do
  
 

  mount Ckeditor::Engine => '/ckeditor'
  resources :announcements
  resources :quizzes
  resources :lessons do
    collection {post :sort}
  end
  resources :units
  resources :tracks
  resources :badges
  resources :resources
  get 'admin/show'
  get 'projects/add', to: 'projects#add'

  resources :classrooms do
    collection { post :importcadata }
  end

  resources :events do
      resources :registrations, only: [:create, :destroy, :add_students_by_classroom, :add_students_by_school] do
          
          resources :signatures, only: [:new, :create, :send] do
              collection do
                  post :callbacks
                  post :sendsigrequest
              end
          end
          
          
          member do
              post :sign
              get :accept
              get :decline
          end
      end
      
      member do
          get :manage
          post :publish
          post :unpublish
          post :add_students_by_classroom
          post :add_students_by_school
      end
  end
  
  
  
  devise_for :users,
    controllers: { registrations: "users/registrations", sessions: "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'static_pages#home'
  

  get 'projects/add', to: 'projects#add'
  get 'editor', to: 'static_pages#editor'

 

  post 'projects/import', to: 'projects#import'

  post '/signatures/callbacks', to: 'signatures#callbacks'
  get '/signatures/callbacks', to: 'signatures#callbacks'
  post 'signatures/authorize_adobe', to: 'signatures#authorize_adobe'
  
  post '/users/invite_teacher', to: 'users#invite_teacher'

  resources :projects
  resources :schools
  resources :teachers
  resources :users  do
      member do
          get :toggle_approved
      end
  end

  resources :classrooms do
      member do 
        get :export_attendance
      end

      resources :enrollments, only: [:create, :destroy, :verify] do
        collection do
          post "verify"
        end
      end
  end
  
  resources :attendance_data do
          member do
              get :toggle_present
          end
  end

  resources :attendance_lists do
      
      member do
          post :toggle_status
          get :record
      end
      
      resources :attendance_data do
          
          member do
              get :mark_as_present
              get :toggle_present
          end
      end

  end

  resources :students do
      collection { post :import }
  end
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :mark_as_read
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  
  resources :notifications, only: [:index, :show] do
      member do
          post :trash
          post :untrash
          post :mark_as_read
          post :mark_as_unread
      end
  end

  resources :messages, only: [:new, :create]
  
  

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.string %></td>
        <td><%= resource.string %></td>
        <td><%= resource.string %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @resource.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @resource.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @resource.string %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>